name: C CI

on: [push, pull_request]

jobs:
  unit_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: teste
      run: ./resources/scripts/test/ci-test.sh
      shell: bash
